version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "10:00"
      timezone: "America/New_York"
    groups:
      helios-lang:
        patterns:
          - "@helios-lang/**"
      koralabs:
        patterns:
          - "@koralabs/**"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/**"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
