pub const legacy_handle_policy_id =
  #"f0ff48bbb7bbe9d59a40f1ce90e9e9d0ff5002ec48f232b49ca0fb9a"

// demi@handle_settings
// hold the settings for the decentralized minting contract
pub const settings_asset_name =
  #"000de14064656d694068616e646c655f73657474696e6773"

// handles_root@handle_settings
// hold MPT root hash of all handles
// NOTE: 
// must be spent every time 
// a new handle is minted
pub const handles_mpt_root_asset_name =
  #"000de14068616e646c65735f726f6f744068616e646c655f73657474696e6773"
