/**
 * Regenerate the committed merged blueprint TypeScript modules
 * (`src/contracts/optimized-blueprint.ts` and `unoptimized-blueprint.ts`)
 * from the per-project Aiken `plutus.json` files.
 *
 * The DeMi off-chain engine consumes a SINGLE merged blueprint that carries
 * validators from TWO Aiken sub-projects compiled with two different
 * toolchains / Plutus versions:
 *
 *   - smart-contract/            → aiken v1.1.22, Plutus V3
 *       demimnt.withdraw, demimntmpt.spend, demiord.spend
 *   - smart-contract-mint-proxy/ → aiken v1.0.29-alpha, Plutus V2 (FROZEN)
 *       demimntprx.mint
 *
 * Because the merged blueprint mixes Plutus versions, the single
 * `preamble.plutusVersion` field can no longer describe every validator.
 * This generator stamps each validator with its own `plutusVersion`
 * ("v2" | "v3") so `src/contracts/validators.ts` can wrap each compiled
 * script with the correct `PlutusVxScript` and hash it with the correct
 * language tag.
 *
 * aiken v1.1.22 emits double-namespaced validator titles
 * (`demimnt.demimnt.withdraw`) plus an `.else` fallback handler per
 * validator. The engine looks validators up by the single-namespace title
 * (`demimnt.withdraw`), so we normalize the titles and drop the `.else`
 * companions (the `.else` handler shares the same compiledCode/hash as its
 * sibling and is not referenced off-chain).
 *
 * Usage:
 *   tsx scripts/generateBlueprints.ts \
 *     --main-optimized   /tmp/optimized-plutus.json \
 *     --main-unoptimized /tmp/unoptimized-plutus.json \
 *     --proxy-optimized   /tmp/proxy-optimized-plutus.json \
 *     --proxy-unoptimized /tmp/proxy-unoptimized-plutus.json
 *
 * The four input files are produced by:
 *   (cd smart-contract && aiken build)             # main-optimized
 *   (cd smart-contract && aiken build -t verbose)  # main-unoptimized
 *   (cd smart-contract-mint-proxy && aiken build)            # proxy-optimized
 *   (cd smart-contract-mint-proxy && aiken build -t verbose) # proxy-unoptimized
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CONTRACTS_DIR = resolve(__dirname, "../src/contracts");

interface Validator {
  title: string;
  plutusVersion?: string;
  compiledCode: string;
  hash: string;
  [k: string]: unknown;
}
interface Blueprint {
  preamble: { plutusVersion: string; [k: string]: unknown };
  validators: Validator[];
  definitions?: Record<string, unknown>;
  [k: string]: unknown;
}

// Map aiken v1.1.22 double-namespaced titles → the single-namespace titles
// the engine looks up. `.else` handlers are dropped.
const NORMALIZE: Record<string, string> = {
  "demimnt.demimnt.withdraw": "demimnt.withdraw",
  "demimntmpt.demimntmpt.spend": "demimntmpt.spend",
  "demiord.demiord.spend": "demiord.spend",
};
// Validators we keep from the main (V3) blueprint, in engine order.
const MAIN_KEEP = new Set(Object.keys(NORMALIZE));
// The single proxy (V2) validator we keep verbatim.
const PROXY_KEEP = "demimntprx.mint";

const parseArgs = (): Record<string, string> => {
  const out: Record<string, string> = {};
  const a = process.argv.slice(2);
  for (let i = 0; i < a.length; i += 2) {
    if (!a[i].startsWith("--")) throw new Error(`bad arg: ${a[i]}`);
    out[a[i].slice(2)] = a[i + 1];
  }
  return out;
};

const load = (p: string): Blueprint =>
  JSON.parse(readFileSync(p, "utf8")) as Blueprint;

const mergeOne = (
  mainBp: Blueprint,
  proxyBp: Blueprint,
): Blueprint => {
  const mainVersion = mainBp.preamble.plutusVersion; // v3
  const proxyVersion = proxyBp.preamble.plutusVersion; // v2

  const validators: Validator[] = [];
  // V3 validators from the main build, normalized + version-tagged.
  for (const v of mainBp.validators) {
    if (!MAIN_KEEP.has(v.title)) continue; // drops .else handlers
    validators.push({
      ...v,
      title: NORMALIZE[v.title],
      plutusVersion: mainVersion,
    });
  }
  // V2 proxy validator, version-tagged.
  for (const v of proxyBp.validators) {
    if (v.title !== PROXY_KEEP) continue;
    validators.push({ ...v, plutusVersion: proxyVersion });
  }

  // Merge definitions. The two builds share no colliding keys (verified),
  // so a shallow union is safe; main wins on any future overlap.
  const definitions: Record<string, unknown> = {
    ...(proxyBp.definitions ?? {}),
    ...(mainBp.definitions ?? {}),
  };

  return {
    // Keep the main (V3) preamble so the file documents the dominant
    // toolchain; per-validator plutusVersion is the source of truth.
    preamble: mainBp.preamble,
    validators,
    definitions,
  };
};

const emit = (filename: string, bp: Blueprint) => {
  const header =
    "// AUTO-GENERATED by scripts/generateBlueprints.ts — do not edit by hand.\n" +
    "// Merged from smart-contract/ (Plutus V3, aiken v1.1.22) and\n" +
    "// smart-contract-mint-proxy/ (Plutus V2, aiken v1.0.29-alpha).\n" +
    "// Each validator carries its own `plutusVersion`.\n";
  const body = `export default ${JSON.stringify(bp, null, 2)};\n`;
  const out = resolve(CONTRACTS_DIR, filename);
  writeFileSync(out, header + body);
  console.log(
    `wrote ${out}: ${bp.validators
      .map((v) => `${v.title}=${v.plutusVersion}:${v.hash}`)
      .join(", ")}`,
  );
};

const main = () => {
  const args = parseArgs();
  const optimized = mergeOne(
    load(args["main-optimized"]),
    load(args["proxy-optimized"]),
  );
  const unoptimized = mergeOne(
    load(args["main-unoptimized"]),
    load(args["proxy-unoptimized"]),
  );
  emit("optimized-blueprint.ts", optimized);
  emit("unoptimized-blueprint.ts", unoptimized);
};

main();
