schema_version: 2
network: preview
build_parameters:
  mint_version: 0
  legacy_policy_id: f0ff48bbb7bbe9d59a40f1ce90e9e9d0ff5002ec48f232b49ca0fb9a
  admin_verification_key_hash: 4da965a049dfd15ed1ee19fba6e2974a0b79fc416dd1796a1f97f5e1
assigned_handles:
  settings:
    - hal@handle_settings
    - hal_root@handle_settings
    - kora@handle_prices
  scripts:
    - mint_proxy@demi_scripts
    - mint_data_v1@demi_scripts
    - mint_v1@demi_scripts
    - orders@demi_scripts
ignored_settings:
  - settings.values.hal_root@handle_settings.mpt_root_hash
settings:
  type: decentralized_minting_settings
  values:
    hal@handle_settings:
      mint_governor: 0d2b729731ca4db1edf8305572a38a60ab12913e8b83a9f2121be41d
      mint_version: 0
      policy_id: 6c32db33a422e0bc2cb535bb850b5a6e9a9572222056d6ddc9cbc26e
      allowed_minters:
        - 976ec349c3a14f58959088e13e98f6cd5a1e8f27f6f3160b25e415ca
      valid_handle_price_assets:
        - f0ff48bbb7bbe9d59a40f1ce90e9e9d0ff5002ec48f232b49ca0fb9a.000de1406b6f72614068616e646c655f707269636573
      treasury_address: addr_test1qz96txepzdhj7ryyse0mq9a97eey2es07dydshr9cgapgyv06l2rv7x0p0vtg5kufwj3avaa909ex8uswsnxnad9ccqsyaga0j
      treasury_fee_percentage: 10
      pz_script_address: addr_test1wzzctdyf9nkgrzqw6vxhaq8mpla7zhzjyjmk6txyu0wsgrgek9nj3
      order_script_hash: 24fe9a2abd4fa926677a65bc8424c755b054790599d4474911a06553
      minting_data_script_hash: 553de54adecc5c9bfa806cbe0341de9c8a8f8ef13d28e86a81284333
    hal_root@handle_settings:
      mpt_root_hash: c614162a20649af2093df773ec4bb1c7d957fe79a1d9d586ac5ce0a2506e2209
    kora@handle_prices:
      current_data: [995000000, 445000000, 150000000, 35000000]
      prev_data: [640000000, 320000000, 80000000, 10000000]
contracts:
  - contract_slug: demimntprx
    script_type: demimntprx
    old_script_type: demi_mint_proxy
    deployment_handle_slug: demimntprx
    build:
      contract_name: demimntprx.mint
      kind: minting_policy
  - contract_slug: demimntmpt
    script_type: demimntmpt
    old_script_type: demi_minting_data
    deployment_handle_slug: demimntmpt
    build:
      contract_name: demimntmpt.spend
      kind: validator
  - contract_slug: demimnt
    script_type: demimnt
    old_script_type: demi_mint
    deployment_handle_slug: demimnt
    build:
      contract_name: demimnt.withdraw
      kind: validator
  - contract_slug: demiord
    script_type: demiord
    old_script_type: demi_orders
    deployment_handle_slug: demiord
    build:
      contract_name: demiord.spend
      kind: validator
